/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-18 at 10:01:03 UTC 
 * Modify at your own risk.
 */

package com.appspot.ad_meet.conference;

import com.appspot.ad_meet.conference.model.Announcement;
import com.appspot.ad_meet.conference.model.Comment;
import com.appspot.ad_meet.conference.model.CommentCollection;
import com.appspot.ad_meet.conference.model.CommentForm;
import com.appspot.ad_meet.conference.model.CommentQueryForm;
import com.appspot.ad_meet.conference.model.ConferenceCollection;
import com.appspot.ad_meet.conference.model.ConferenceForm;
import com.appspot.ad_meet.conference.model.ConferenceQueryForm;
import com.appspot.ad_meet.conference.model.KickerForm;
import com.appspot.ad_meet.conference.model.Profile;
import com.appspot.ad_meet.conference.model.ProfileCollection;
import com.appspot.ad_meet.conference.model.ProfileForm;
import com.appspot.ad_meet.conference.model.ProfileQueryForm;
import com.appspot.ad_meet.conference.model.WrappedBoolean;

/**
 * Service definition for Conference (v1).
 *
 * <p>
 * API for AdMeet Backend application.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link com.appspot.ad_meet.conference.ConferenceRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Conference extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the conference library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ad-meet.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "conference/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Conference(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Conference(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "createComment".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link CreateComment#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.CommentForm}
   * @return the request
   */
  public CreateComment createComment(CommentForm content) throws java.io.IOException {
    CreateComment result = new CreateComment(content);
    initialize(result);
    return result;
  }

  public class CreateComment extends ConferenceRequest<Comment> {

    private static final String REST_PATH = "createcomment";

    /**
     * Create a request for the method "createComment".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link CreateComment#execute()} method to invoke the remote
     * operation. <p> {@link CreateComment#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.CommentForm}
     * @since 1.13
     */
    protected CreateComment(CommentForm content) {
      super(Conference.this, "POST", REST_PATH, content, Comment.class);
    }

    @Override
    public CreateComment setAlt(String alt) {
      return (CreateComment) super.setAlt(alt);
    }

    @Override
    public CreateComment setFields(String fields) {
      return (CreateComment) super.setFields(fields);
    }

    @Override
    public CreateComment setKey(String key) {
      return (CreateComment) super.setKey(key);
    }

    @Override
    public CreateComment setOauthToken(String oauthToken) {
      return (CreateComment) super.setOauthToken(oauthToken);
    }

    @Override
    public CreateComment setPrettyPrint(Boolean prettyPrint) {
      return (CreateComment) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CreateComment setQuotaUser(String quotaUser) {
      return (CreateComment) super.setQuotaUser(quotaUser);
    }

    @Override
    public CreateComment setUserIp(String userIp) {
      return (CreateComment) super.setUserIp(userIp);
    }

    @Override
    public CreateComment set(String parameterName, Object value) {
      return (CreateComment) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "createConference".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link CreateConference#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.ConferenceForm}
   * @return the request
   */
  public CreateConference createConference(ConferenceForm content) throws java.io.IOException {
    CreateConference result = new CreateConference(content);
    initialize(result);
    return result;
  }

  public class CreateConference extends ConferenceRequest<com.appspot.ad_meet.conference.model.Conference> {

    private static final String REST_PATH = "conference";

    /**
     * Create a request for the method "createConference".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link CreateConference#execute()} method to invoke the remote
     * operation. <p> {@link CreateConference#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.ConferenceForm}
     * @since 1.13
     */
    protected CreateConference(ConferenceForm content) {
      super(Conference.this, "POST", REST_PATH, content, com.appspot.ad_meet.conference.model.Conference.class);
    }

    @Override
    public CreateConference setAlt(String alt) {
      return (CreateConference) super.setAlt(alt);
    }

    @Override
    public CreateConference setFields(String fields) {
      return (CreateConference) super.setFields(fields);
    }

    @Override
    public CreateConference setKey(String key) {
      return (CreateConference) super.setKey(key);
    }

    @Override
    public CreateConference setOauthToken(String oauthToken) {
      return (CreateConference) super.setOauthToken(oauthToken);
    }

    @Override
    public CreateConference setPrettyPrint(Boolean prettyPrint) {
      return (CreateConference) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CreateConference setQuotaUser(String quotaUser) {
      return (CreateConference) super.setQuotaUser(quotaUser);
    }

    @Override
    public CreateConference setUserIp(String userIp) {
      return (CreateConference) super.setUserIp(userIp);
    }

    @Override
    public CreateConference set(String parameterName, Object value) {
      return (CreateConference) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getAnnouncement".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetAnnouncement#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetAnnouncement getAnnouncement() throws java.io.IOException {
    GetAnnouncement result = new GetAnnouncement();
    initialize(result);
    return result;
  }

  public class GetAnnouncement extends ConferenceRequest<Announcement> {

    private static final String REST_PATH = "announcement";

    /**
     * Create a request for the method "getAnnouncement".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetAnnouncement#execute()} method to invoke the remote
     * operation. <p> {@link GetAnnouncement#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAnnouncement() {
      super(Conference.this, "GET", REST_PATH, null, Announcement.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAnnouncement setAlt(String alt) {
      return (GetAnnouncement) super.setAlt(alt);
    }

    @Override
    public GetAnnouncement setFields(String fields) {
      return (GetAnnouncement) super.setFields(fields);
    }

    @Override
    public GetAnnouncement setKey(String key) {
      return (GetAnnouncement) super.setKey(key);
    }

    @Override
    public GetAnnouncement setOauthToken(String oauthToken) {
      return (GetAnnouncement) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAnnouncement setPrettyPrint(Boolean prettyPrint) {
      return (GetAnnouncement) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAnnouncement setQuotaUser(String quotaUser) {
      return (GetAnnouncement) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAnnouncement setUserIp(String userIp) {
      return (GetAnnouncement) super.setUserIp(userIp);
    }

    @Override
    public GetAnnouncement set(String parameterName, Object value) {
      return (GetAnnouncement) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getComments".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetComments#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.CommentQueryForm}
   * @return the request
   */
  public GetComments getComments(CommentQueryForm content) throws java.io.IOException {
    GetComments result = new GetComments(content);
    initialize(result);
    return result;
  }

  public class GetComments extends ConferenceRequest<CommentCollection> {

    private static final String REST_PATH = "getComments";

    /**
     * Create a request for the method "getComments".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetComments#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetComments#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.CommentQueryForm}
     * @since 1.13
     */
    protected GetComments(CommentQueryForm content) {
      super(Conference.this, "POST", REST_PATH, content, CommentCollection.class);
    }

    @Override
    public GetComments setAlt(String alt) {
      return (GetComments) super.setAlt(alt);
    }

    @Override
    public GetComments setFields(String fields) {
      return (GetComments) super.setFields(fields);
    }

    @Override
    public GetComments setKey(String key) {
      return (GetComments) super.setKey(key);
    }

    @Override
    public GetComments setOauthToken(String oauthToken) {
      return (GetComments) super.setOauthToken(oauthToken);
    }

    @Override
    public GetComments setPrettyPrint(Boolean prettyPrint) {
      return (GetComments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetComments setQuotaUser(String quotaUser) {
      return (GetComments) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetComments setUserIp(String userIp) {
      return (GetComments) super.setUserIp(userIp);
    }

    @Override
    public GetComments set(String parameterName, Object value) {
      return (GetComments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getConference".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetConference#execute()} method to invoke the remote operation.
   *
   * @param websafeConferenceKey
   * @return the request
   */
  public GetConference getConference(String websafeConferenceKey) throws java.io.IOException {
    GetConference result = new GetConference(websafeConferenceKey);
    initialize(result);
    return result;
  }

  public class GetConference extends ConferenceRequest<com.appspot.ad_meet.conference.model.Conference> {

    private static final String REST_PATH = "conference/{websafeConferenceKey}";

    /**
     * Create a request for the method "getConference".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetConference#execute()} method to invoke the remote
     * operation. <p> {@link GetConference#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param websafeConferenceKey
     * @since 1.13
     */
    protected GetConference(String websafeConferenceKey) {
      super(Conference.this, "GET", REST_PATH, null, com.appspot.ad_meet.conference.model.Conference.class);
      this.websafeConferenceKey = com.google.api.client.util.Preconditions.checkNotNull(websafeConferenceKey, "Required parameter websafeConferenceKey must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetConference setAlt(String alt) {
      return (GetConference) super.setAlt(alt);
    }

    @Override
    public GetConference setFields(String fields) {
      return (GetConference) super.setFields(fields);
    }

    @Override
    public GetConference setKey(String key) {
      return (GetConference) super.setKey(key);
    }

    @Override
    public GetConference setOauthToken(String oauthToken) {
      return (GetConference) super.setOauthToken(oauthToken);
    }

    @Override
    public GetConference setPrettyPrint(Boolean prettyPrint) {
      return (GetConference) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetConference setQuotaUser(String quotaUser) {
      return (GetConference) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetConference setUserIp(String userIp) {
      return (GetConference) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private String websafeConferenceKey;

    /**

     */
    public String getWebsafeConferenceKey() {
      return websafeConferenceKey;
    }

    public GetConference setWebsafeConferenceKey(String websafeConferenceKey) {
      this.websafeConferenceKey = websafeConferenceKey;
      return this;
    }

    @Override
    public GetConference set(String parameterName, Object value) {
      return (GetConference) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getConferencesCreated".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetConferencesCreated#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetConferencesCreated getConferencesCreated() throws java.io.IOException {
    GetConferencesCreated result = new GetConferencesCreated();
    initialize(result);
    return result;
  }

  public class GetConferencesCreated extends ConferenceRequest<ConferenceCollection> {

    private static final String REST_PATH = "getConferencesCreated";

    /**
     * Create a request for the method "getConferencesCreated".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetConferencesCreated#execute()} method to invoke the
     * remote operation. <p> {@link GetConferencesCreated#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetConferencesCreated() {
      super(Conference.this, "POST", REST_PATH, null, ConferenceCollection.class);
    }

    @Override
    public GetConferencesCreated setAlt(String alt) {
      return (GetConferencesCreated) super.setAlt(alt);
    }

    @Override
    public GetConferencesCreated setFields(String fields) {
      return (GetConferencesCreated) super.setFields(fields);
    }

    @Override
    public GetConferencesCreated setKey(String key) {
      return (GetConferencesCreated) super.setKey(key);
    }

    @Override
    public GetConferencesCreated setOauthToken(String oauthToken) {
      return (GetConferencesCreated) super.setOauthToken(oauthToken);
    }

    @Override
    public GetConferencesCreated setPrettyPrint(Boolean prettyPrint) {
      return (GetConferencesCreated) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetConferencesCreated setQuotaUser(String quotaUser) {
      return (GetConferencesCreated) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetConferencesCreated setUserIp(String userIp) {
      return (GetConferencesCreated) super.setUserIp(userIp);
    }

    @Override
    public GetConferencesCreated set(String parameterName, Object value) {
      return (GetConferencesCreated) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getConferencesToAttend".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetConferencesToAttend#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetConferencesToAttend getConferencesToAttend() throws java.io.IOException {
    GetConferencesToAttend result = new GetConferencesToAttend();
    initialize(result);
    return result;
  }

  public class GetConferencesToAttend extends ConferenceRequest<ConferenceCollection> {

    private static final String REST_PATH = "getConferencesToAttend";

    /**
     * Create a request for the method "getConferencesToAttend".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetConferencesToAttend#execute()} method to invoke the
     * remote operation. <p> {@link GetConferencesToAttend#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetConferencesToAttend() {
      super(Conference.this, "GET", REST_PATH, null, ConferenceCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetConferencesToAttend setAlt(String alt) {
      return (GetConferencesToAttend) super.setAlt(alt);
    }

    @Override
    public GetConferencesToAttend setFields(String fields) {
      return (GetConferencesToAttend) super.setFields(fields);
    }

    @Override
    public GetConferencesToAttend setKey(String key) {
      return (GetConferencesToAttend) super.setKey(key);
    }

    @Override
    public GetConferencesToAttend setOauthToken(String oauthToken) {
      return (GetConferencesToAttend) super.setOauthToken(oauthToken);
    }

    @Override
    public GetConferencesToAttend setPrettyPrint(Boolean prettyPrint) {
      return (GetConferencesToAttend) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetConferencesToAttend setQuotaUser(String quotaUser) {
      return (GetConferencesToAttend) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetConferencesToAttend setUserIp(String userIp) {
      return (GetConferencesToAttend) super.setUserIp(userIp);
    }

    @Override
    public GetConferencesToAttend set(String parameterName, Object value) {
      return (GetConferencesToAttend) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getParticipants".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetParticipants#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.CommentQueryForm}
   * @return the request
   */
  public GetParticipants getParticipants(CommentQueryForm content) throws java.io.IOException {
    GetParticipants result = new GetParticipants(content);
    initialize(result);
    return result;
  }

  public class GetParticipants extends ConferenceRequest<ProfileCollection> {

    private static final String REST_PATH = "getParticipants";

    /**
     * Create a request for the method "getParticipants".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetParticipants#execute()} method to invoke the remote
     * operation. <p> {@link GetParticipants#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.CommentQueryForm}
     * @since 1.13
     */
    protected GetParticipants(CommentQueryForm content) {
      super(Conference.this, "POST", REST_PATH, content, ProfileCollection.class);
    }

    @Override
    public GetParticipants setAlt(String alt) {
      return (GetParticipants) super.setAlt(alt);
    }

    @Override
    public GetParticipants setFields(String fields) {
      return (GetParticipants) super.setFields(fields);
    }

    @Override
    public GetParticipants setKey(String key) {
      return (GetParticipants) super.setKey(key);
    }

    @Override
    public GetParticipants setOauthToken(String oauthToken) {
      return (GetParticipants) super.setOauthToken(oauthToken);
    }

    @Override
    public GetParticipants setPrettyPrint(Boolean prettyPrint) {
      return (GetParticipants) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetParticipants setQuotaUser(String quotaUser) {
      return (GetParticipants) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetParticipants setUserIp(String userIp) {
      return (GetParticipants) super.setUserIp(userIp);
    }

    @Override
    public GetParticipants set(String parameterName, Object value) {
      return (GetParticipants) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getProfile".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetProfile#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetProfile getProfile() throws java.io.IOException {
    GetProfile result = new GetProfile();
    initialize(result);
    return result;
  }

  public class GetProfile extends ConferenceRequest<Profile> {

    private static final String REST_PATH = "profile";

    /**
     * Create a request for the method "getProfile".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetProfile#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetProfile#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetProfile() {
      super(Conference.this, "GET", REST_PATH, null, Profile.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProfile setAlt(String alt) {
      return (GetProfile) super.setAlt(alt);
    }

    @Override
    public GetProfile setFields(String fields) {
      return (GetProfile) super.setFields(fields);
    }

    @Override
    public GetProfile setKey(String key) {
      return (GetProfile) super.setKey(key);
    }

    @Override
    public GetProfile setOauthToken(String oauthToken) {
      return (GetProfile) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProfile setPrettyPrint(Boolean prettyPrint) {
      return (GetProfile) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProfile setQuotaUser(String quotaUser) {
      return (GetProfile) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProfile setUserIp(String userIp) {
      return (GetProfile) super.setUserIp(userIp);
    }

    @Override
    public GetProfile set(String parameterName, Object value) {
      return (GetProfile) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getProfileFromId".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link GetProfileFromId#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.ProfileQueryForm}
   * @return the request
   */
  public GetProfileFromId getProfileFromId(ProfileQueryForm content) throws java.io.IOException {
    GetProfileFromId result = new GetProfileFromId(content);
    initialize(result);
    return result;
  }

  public class GetProfileFromId extends ConferenceRequest<Profile> {

    private static final String REST_PATH = "getProfileFromId";

    /**
     * Create a request for the method "getProfileFromId".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link GetProfileFromId#execute()} method to invoke the remote
     * operation. <p> {@link GetProfileFromId#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.ProfileQueryForm}
     * @since 1.13
     */
    protected GetProfileFromId(ProfileQueryForm content) {
      super(Conference.this, "POST", REST_PATH, content, Profile.class);
    }

    @Override
    public GetProfileFromId setAlt(String alt) {
      return (GetProfileFromId) super.setAlt(alt);
    }

    @Override
    public GetProfileFromId setFields(String fields) {
      return (GetProfileFromId) super.setFields(fields);
    }

    @Override
    public GetProfileFromId setKey(String key) {
      return (GetProfileFromId) super.setKey(key);
    }

    @Override
    public GetProfileFromId setOauthToken(String oauthToken) {
      return (GetProfileFromId) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProfileFromId setPrettyPrint(Boolean prettyPrint) {
      return (GetProfileFromId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProfileFromId setQuotaUser(String quotaUser) {
      return (GetProfileFromId) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProfileFromId setUserIp(String userIp) {
      return (GetProfileFromId) super.setUserIp(userIp);
    }

    @Override
    public GetProfileFromId set(String parameterName, Object value) {
      return (GetProfileFromId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "kickFromConference".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link KickFromConference#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.KickerForm}
   * @return the request
   */
  public KickFromConference kickFromConference(KickerForm content) throws java.io.IOException {
    KickFromConference result = new KickFromConference(content);
    initialize(result);
    return result;
  }

  public class KickFromConference extends ConferenceRequest<WrappedBoolean> {

    private static final String REST_PATH = "kickFromConference";

    /**
     * Create a request for the method "kickFromConference".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link KickFromConference#execute()} method to invoke the remote
     * operation. <p> {@link KickFromConference#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.KickerForm}
     * @since 1.13
     */
    protected KickFromConference(KickerForm content) {
      super(Conference.this, "POST", REST_PATH, content, WrappedBoolean.class);
    }

    @Override
    public KickFromConference setAlt(String alt) {
      return (KickFromConference) super.setAlt(alt);
    }

    @Override
    public KickFromConference setFields(String fields) {
      return (KickFromConference) super.setFields(fields);
    }

    @Override
    public KickFromConference setKey(String key) {
      return (KickFromConference) super.setKey(key);
    }

    @Override
    public KickFromConference setOauthToken(String oauthToken) {
      return (KickFromConference) super.setOauthToken(oauthToken);
    }

    @Override
    public KickFromConference setPrettyPrint(Boolean prettyPrint) {
      return (KickFromConference) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public KickFromConference setQuotaUser(String quotaUser) {
      return (KickFromConference) super.setQuotaUser(quotaUser);
    }

    @Override
    public KickFromConference setUserIp(String userIp) {
      return (KickFromConference) super.setUserIp(userIp);
    }

    @Override
    public KickFromConference set(String parameterName, Object value) {
      return (KickFromConference) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "queryConferences".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link QueryConferences#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.ConferenceQueryForm}
   * @return the request
   */
  public QueryConferences queryConferences(ConferenceQueryForm content) throws java.io.IOException {
    QueryConferences result = new QueryConferences(content);
    initialize(result);
    return result;
  }

  public class QueryConferences extends ConferenceRequest<ConferenceCollection> {

    private static final String REST_PATH = "queryConferences";

    /**
     * Create a request for the method "queryConferences".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link QueryConferences#execute()} method to invoke the remote
     * operation. <p> {@link QueryConferences#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.ConferenceQueryForm}
     * @since 1.13
     */
    protected QueryConferences(ConferenceQueryForm content) {
      super(Conference.this, "POST", REST_PATH, content, ConferenceCollection.class);
    }

    @Override
    public QueryConferences setAlt(String alt) {
      return (QueryConferences) super.setAlt(alt);
    }

    @Override
    public QueryConferences setFields(String fields) {
      return (QueryConferences) super.setFields(fields);
    }

    @Override
    public QueryConferences setKey(String key) {
      return (QueryConferences) super.setKey(key);
    }

    @Override
    public QueryConferences setOauthToken(String oauthToken) {
      return (QueryConferences) super.setOauthToken(oauthToken);
    }

    @Override
    public QueryConferences setPrettyPrint(Boolean prettyPrint) {
      return (QueryConferences) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QueryConferences setQuotaUser(String quotaUser) {
      return (QueryConferences) super.setQuotaUser(quotaUser);
    }

    @Override
    public QueryConferences setUserIp(String userIp) {
      return (QueryConferences) super.setUserIp(userIp);
    }

    @Override
    public QueryConferences set(String parameterName, Object value) {
      return (QueryConferences) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registerForConference".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link RegisterForConference#execute()} method to invoke the remote
   * operation.
   *
   * @param websafeConferenceKey
   * @return the request
   */
  public RegisterForConference registerForConference(String websafeConferenceKey) throws java.io.IOException {
    RegisterForConference result = new RegisterForConference(websafeConferenceKey);
    initialize(result);
    return result;
  }

  public class RegisterForConference extends ConferenceRequest<WrappedBoolean> {

    private static final String REST_PATH = "conference/{websafeConferenceKey}/registration";

    /**
     * Create a request for the method "registerForConference".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link RegisterForConference#execute()} method to invoke the
     * remote operation. <p> {@link RegisterForConference#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param websafeConferenceKey
     * @since 1.13
     */
    protected RegisterForConference(String websafeConferenceKey) {
      super(Conference.this, "POST", REST_PATH, null, WrappedBoolean.class);
      this.websafeConferenceKey = com.google.api.client.util.Preconditions.checkNotNull(websafeConferenceKey, "Required parameter websafeConferenceKey must be specified.");
    }

    @Override
    public RegisterForConference setAlt(String alt) {
      return (RegisterForConference) super.setAlt(alt);
    }

    @Override
    public RegisterForConference setFields(String fields) {
      return (RegisterForConference) super.setFields(fields);
    }

    @Override
    public RegisterForConference setKey(String key) {
      return (RegisterForConference) super.setKey(key);
    }

    @Override
    public RegisterForConference setOauthToken(String oauthToken) {
      return (RegisterForConference) super.setOauthToken(oauthToken);
    }

    @Override
    public RegisterForConference setPrettyPrint(Boolean prettyPrint) {
      return (RegisterForConference) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegisterForConference setQuotaUser(String quotaUser) {
      return (RegisterForConference) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegisterForConference setUserIp(String userIp) {
      return (RegisterForConference) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private String websafeConferenceKey;

    /**

     */
    public String getWebsafeConferenceKey() {
      return websafeConferenceKey;
    }

    public RegisterForConference setWebsafeConferenceKey(String websafeConferenceKey) {
      this.websafeConferenceKey = websafeConferenceKey;
      return this;
    }

    @Override
    public RegisterForConference set(String parameterName, Object value) {
      return (RegisterForConference) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "saveProfile".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link SaveProfile#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ad_meet.conference.model.ProfileForm}
   * @return the request
   */
  public SaveProfile saveProfile(ProfileForm content) throws java.io.IOException {
    SaveProfile result = new SaveProfile(content);
    initialize(result);
    return result;
  }

  public class SaveProfile extends ConferenceRequest<Profile> {

    private static final String REST_PATH = "profile";

    /**
     * Create a request for the method "saveProfile".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link SaveProfile#execute()} method to invoke the remote
     * operation. <p> {@link
     * SaveProfile#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.ad_meet.conference.model.ProfileForm}
     * @since 1.13
     */
    protected SaveProfile(ProfileForm content) {
      super(Conference.this, "POST", REST_PATH, content, Profile.class);
    }

    @Override
    public SaveProfile setAlt(String alt) {
      return (SaveProfile) super.setAlt(alt);
    }

    @Override
    public SaveProfile setFields(String fields) {
      return (SaveProfile) super.setFields(fields);
    }

    @Override
    public SaveProfile setKey(String key) {
      return (SaveProfile) super.setKey(key);
    }

    @Override
    public SaveProfile setOauthToken(String oauthToken) {
      return (SaveProfile) super.setOauthToken(oauthToken);
    }

    @Override
    public SaveProfile setPrettyPrint(Boolean prettyPrint) {
      return (SaveProfile) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SaveProfile setQuotaUser(String quotaUser) {
      return (SaveProfile) super.setQuotaUser(quotaUser);
    }

    @Override
    public SaveProfile setUserIp(String userIp) {
      return (SaveProfile) super.setUserIp(userIp);
    }

    @Override
    public SaveProfile set(String parameterName, Object value) {
      return (SaveProfile) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "unregisterFromConference".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link UnregisterFromConference#execute()} method to invoke the remote
   * operation.
   *
   * @param websafeConferenceKey
   * @return the request
   */
  public UnregisterFromConference unregisterFromConference(String websafeConferenceKey) throws java.io.IOException {
    UnregisterFromConference result = new UnregisterFromConference(websafeConferenceKey);
    initialize(result);
    return result;
  }

  public class UnregisterFromConference extends ConferenceRequest<WrappedBoolean> {

    private static final String REST_PATH = "conference/{websafeConferenceKey}/registration";

    /**
     * Create a request for the method "unregisterFromConference".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link UnregisterFromConference#execute()} method to invoke the
     * remote operation. <p> {@link UnregisterFromConference#initialize(com.google.api.client.googleap
     * is.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param websafeConferenceKey
     * @since 1.13
     */
    protected UnregisterFromConference(String websafeConferenceKey) {
      super(Conference.this, "DELETE", REST_PATH, null, WrappedBoolean.class);
      this.websafeConferenceKey = com.google.api.client.util.Preconditions.checkNotNull(websafeConferenceKey, "Required parameter websafeConferenceKey must be specified.");
    }

    @Override
    public UnregisterFromConference setAlt(String alt) {
      return (UnregisterFromConference) super.setAlt(alt);
    }

    @Override
    public UnregisterFromConference setFields(String fields) {
      return (UnregisterFromConference) super.setFields(fields);
    }

    @Override
    public UnregisterFromConference setKey(String key) {
      return (UnregisterFromConference) super.setKey(key);
    }

    @Override
    public UnregisterFromConference setOauthToken(String oauthToken) {
      return (UnregisterFromConference) super.setOauthToken(oauthToken);
    }

    @Override
    public UnregisterFromConference setPrettyPrint(Boolean prettyPrint) {
      return (UnregisterFromConference) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UnregisterFromConference setQuotaUser(String quotaUser) {
      return (UnregisterFromConference) super.setQuotaUser(quotaUser);
    }

    @Override
    public UnregisterFromConference setUserIp(String userIp) {
      return (UnregisterFromConference) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private String websafeConferenceKey;

    /**

     */
    public String getWebsafeConferenceKey() {
      return websafeConferenceKey;
    }

    public UnregisterFromConference setWebsafeConferenceKey(String websafeConferenceKey) {
      this.websafeConferenceKey = websafeConferenceKey;
      return this;
    }

    @Override
    public UnregisterFromConference set(String parameterName, Object value) {
      return (UnregisterFromConference) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateConference".
   *
   * This request holds the parameters needed by the conference server.  After setting any optional
   * parameters, call the {@link UpdateConference#execute()} method to invoke the remote operation.
   *
   * @param websafeConferenceKey
   * @param content the {@link com.appspot.ad_meet.conference.model.ConferenceForm}
   * @return the request
   */
  public UpdateConference updateConference(String websafeConferenceKey, ConferenceForm content) throws java.io.IOException {
    UpdateConference result = new UpdateConference(websafeConferenceKey, content);
    initialize(result);
    return result;
  }

  public class UpdateConference extends ConferenceRequest<com.appspot.ad_meet.conference.model.Conference> {

    private static final String REST_PATH = "conference/{websafeConferenceKey}";

    /**
     * Create a request for the method "updateConference".
     *
     * This request holds the parameters needed by the the conference server.  After setting any
     * optional parameters, call the {@link UpdateConference#execute()} method to invoke the remote
     * operation. <p> {@link UpdateConference#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param websafeConferenceKey
     * @param content the {@link com.appspot.ad_meet.conference.model.ConferenceForm}
     * @since 1.13
     */
    protected UpdateConference(String websafeConferenceKey, ConferenceForm content) {
      super(Conference.this, "PUT", REST_PATH, content, com.appspot.ad_meet.conference.model.Conference.class);
      this.websafeConferenceKey = com.google.api.client.util.Preconditions.checkNotNull(websafeConferenceKey, "Required parameter websafeConferenceKey must be specified.");
    }

    @Override
    public UpdateConference setAlt(String alt) {
      return (UpdateConference) super.setAlt(alt);
    }

    @Override
    public UpdateConference setFields(String fields) {
      return (UpdateConference) super.setFields(fields);
    }

    @Override
    public UpdateConference setKey(String key) {
      return (UpdateConference) super.setKey(key);
    }

    @Override
    public UpdateConference setOauthToken(String oauthToken) {
      return (UpdateConference) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateConference setPrettyPrint(Boolean prettyPrint) {
      return (UpdateConference) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateConference setQuotaUser(String quotaUser) {
      return (UpdateConference) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateConference setUserIp(String userIp) {
      return (UpdateConference) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private String websafeConferenceKey;

    /**

     */
    public String getWebsafeConferenceKey() {
      return websafeConferenceKey;
    }

    public UpdateConference setWebsafeConferenceKey(String websafeConferenceKey) {
      this.websafeConferenceKey = websafeConferenceKey;
      return this;
    }

    @Override
    public UpdateConference set(String parameterName, Object value) {
      return (UpdateConference) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Conference}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Conference}. */
    @Override
    public Conference build() {
      return new Conference(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link com.appspot.ad_meet.conference.ConferenceRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setConferenceRequestInitializer(
        ConferenceRequestInitializer conferenceRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(conferenceRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
