/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-16 at 01:32:32 UTC 
 * Modify at your own risk.
 */

package com.appspot.ad_meet.conference.model;

/**
 * Model definition for Conference.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the conference. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Conference extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String city;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<String> comments;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer maxAttendees;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer month;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String organizerDisplayName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<String> participants;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer seatsAvailable;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime startDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<String> topics;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String websafeKey;

  /**
   * @return value or {@code null} for none
   */
  public String getCity() {
    return city;
  }

  /**
   * @param city city or {@code null} for none
   */
  public Conference setCity(String city) {
    this.city = city;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<String> getComments() {
    return comments;
  }

  /**
   * @param comments comments or {@code null} for none
   */
  public Conference setComments(java.util.List<String> comments) {
    this.comments = comments;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public Conference setDescription(String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Conference setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getMaxAttendees() {
    return maxAttendees;
  }

  /**
   * @param maxAttendees maxAttendees or {@code null} for none
   */
  public Conference setMaxAttendees(Integer maxAttendees) {
    this.maxAttendees = maxAttendees;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getMonth() {
    return month;
  }

  /**
   * @param month month or {@code null} for none
   */
  public Conference setMonth(Integer month) {
    this.month = month;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Conference setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getOrganizerDisplayName() {
    return organizerDisplayName;
  }

  /**
   * @param organizerDisplayName organizerDisplayName or {@code null} for none
   */
  public Conference setOrganizerDisplayName(String organizerDisplayName) {
    this.organizerDisplayName = organizerDisplayName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<String> getParticipants() {
    return participants;
  }

  /**
   * @param participants participants or {@code null} for none
   */
  public Conference setParticipants(java.util.List<String> participants) {
    this.participants = participants;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getSeatsAvailable() {
    return seatsAvailable;
  }

  /**
   * @param seatsAvailable seatsAvailable or {@code null} for none
   */
  public Conference setSeatsAvailable(Integer seatsAvailable) {
    this.seatsAvailable = seatsAvailable;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getStartDate() {
    return startDate;
  }

  /**
   * @param startDate startDate or {@code null} for none
   */
  public Conference setStartDate(com.google.api.client.util.DateTime startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<String> getTopics() {
    return topics;
  }

  /**
   * @param topics topics or {@code null} for none
   */
  public Conference setTopics(java.util.List<String> topics) {
    this.topics = topics;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getWebsafeKey() {
    return websafeKey;
  }

  /**
   * @param websafeKey websafeKey or {@code null} for none
   */
  public Conference setWebsafeKey(String websafeKey) {
    this.websafeKey = websafeKey;
    return this;
  }

  @Override
  public Conference set(String fieldName, Object value) {
    return (Conference) super.set(fieldName, value);
  }

  @Override
  public Conference clone() {
    return (Conference) super.clone();
  }

}
